name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore src/z_planner_bot/

    - name: Build
      run: dotnet build src/z_planner_bot/ --configuration Release

    - name: Run bot
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      run: dotnet run --project src/z_planner_bot/
